# rules are determined with what fields are present in the actions section
# MMS103 specific rules
- id: "MMS103_FAIL_LOW_COVERAGE"
  description: "Low coverage detected"
  conditions:
    - field: TEST_COVERAGE
      operator: "=="
      value: false
    - field: COVERAGE
      operator: "<"
      value: 40
  actions:
    - field: MMS103
      value: "FAIL"
    - field: COMMENT
      value: "FAIL due to low coverage"

- id: "MMS103_PASS_GENOME_SIZE"
  description: "Genome size within acceptable range"
  conditions:
    - field: TEST_GENOME_SIZE_KMER
      operator: "=="
      value: false
    - field: GENOME_SIZE_KMER
      operator: "between_pct"
      min_field: GENOME_SIZE_MIN
      max_field: GENOME_SIZE_MAX
      pct: 0.10
  actions:
    - field: MMS103
      value: "PASS"
    - field: COMMENT
      value: "Manual PASS as KMER genome size within 10% of acceptable range"

- id: "MMS103_PASS_GENUS_MATCH"
  description: "Manual PASS when genus matches between SPECIES_OBS and SPECIES_EXP despite failed species test"
  conditions:
    - field: TEST_SPECIES
      operator: "=="
      value: false
    - field: SPECIES_EXP
      operator: "contains"
      value: " species"
    - field: SPECIES_OBS
      operator: "genus_level_match"
      value: true
  actions:
    - field: MMS103
      value: "PASS"
    - field: COMMENT
      value: "MMS103 Manual PASS as no sp. supplied for sp. EXP and match at genus level to sp. OBS"

- id: "MMS103_PASS_SPECIES_SSP_INCL"
  description: "PASS when species is a subspecies of the expected species"
  conditions:
    - field: TEST_SPECIES
      operator: "=="
      value: false
    - field: SPECIES_EXP
      operator: "contains"
      value: " ssp "
    - field: SPECIES_OBS
      operator: "species_subspecies_match"
      value: true
  actions:
    - field: MMS103
      value: "PASS"
    - field: COMMENT
      value: "MMS103 Manual PASS as ssp incl. in sp. EXP"

- id: "MMS103_FLAG_SPECIES_UNRESOLVED"
  description: "FLAG when species could not be resolved below genus level"
  conditions:
    - field: TEST_SPECIES
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "contains"
      value: " species"
    - field: SPECIES_EXP
      operator: "genus_level_match"
      value: true
  actions:
    - field: MMS103
      value: "FLAG"
    - field: COMMENT
      value: "MMS103 FLAG as sp. OBS match at genus level to sp. EXP and species could not be resolved below the genus level"

- id: "MMS103_FLAG_SPECIES_MISMATCH_GENUS_MATCH"
  description: "FLAG when species are different but genus matches"
  conditions:
    - field: TEST_SPECIES
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "species_different_genus_match"
      value: true
  actions:
    - field: MMS103
      value: "FLAG"
    - field: COMMENT
      value: "MMS103 FLAG as sp. OBS match at genus level to sp. EXP"

- id: "MMS103_FAIL_SPECIES_MISMATCH"
  description: "FAIL when species have different genera"
  conditions:
    - field: TEST_SPECIES
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "species_genus_mismatch"
      value: true
  actions:
    - field: MMS103
      value: "FAIL"
    - field: COMMENT
      value: "FAIL due to species mismatch"

# MMS109 specific rules
- id: "MMS109_SCHEME_COMPATIBLE"
  description: "Manual PASS when MLST scheme is appropriate for species despite failed scheme test"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "species_scheme_compatible"
      value: true
  actions:
    - field: COMMENT
      value: "MLST scheme appropriate for SPECIES_OBS"  

- id: "MMS109_FLAG_NOVEL_ALLELE"
  description: "Novel allele detected when TEST_SCHEME is true"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: true
    - field: TEST_ST
      operator: "=="
      value: false
    - field: TEST_MLST_ALLELES
      operator: "=="
      value: "NOVEL ALLELE"
  actions:
    - field: MMS109
      value: "FLAG"
    - field: COMMENT
      value: "MMS109 FLAG as NOVEL ALLELE resulted in no ST"

- id: "MMS109_FLAG_NOVEL_ALLELE_COMPATIBLE"
  description: "Novel allele detected when species is compatible with scheme"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "species_scheme_compatible"
      value: true
    - field: TEST_ST
      operator: "=="
      value: false
    - field: TEST_MLST_ALLELES
      operator: "=="
      value: "NOVEL ALLELE"
  actions:
    - field: MMS109
      value: "FLAG"
    - field: COMMENT
      value: "MMS109 FLAG as NOVEL ALLELE resulted in no ST; MLST scheme appropriate for SPECIES_OBS"

- id: "MMS109_PARTIAL"
  description: "Partial MLST scheme when TEST_SCHEME is true"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: true
    - field: TEST_ST
      operator: "=="
      value: false
    - field: TEST_MLST_ALLELES
      operator: "contains"
      value: "PARTIAL"
  actions:
    - field: MMS109
      value: "FLAG"
    - field: COMMENT
      value: "MMS109 FLAG as PARTIAL MLST scheme resulted in no ST"

- id: "MMS109_PARTIAL_COMPATIBLE"
  description: "Partial MLST scheme when species is compatible with scheme"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: false
    - field: SPECIES_OBS
      operator: "species_scheme_compatible"
      value: true
    - field: TEST_ST
      operator: "=="
      value: false
    - field: TEST_MLST_ALLELES
      operator: "contains"
      value: "PARTIAL"
  actions:
    - field: MMS109
      value: "FLAG"
    - field: COMMENT
      value: "MMS109 FLAG as PARTIAL MLST scheme resulted in no ST; MLST scheme appropriate for SPECIES_OBS"

- id: "MMS109_PASS_SCHEME_COMPATIBLE_MANUAL_PASS"
  description: "Manual PASS when MLST scheme is appropriate for species despite failed scheme test"
  conditions:
    - field: TEST_SCHEME
      operator: "=="
      value: false
    - field: TEST_ST
      operator: "=="
      value: true
    - field: TEST_MLST_ALLELES
      operator: "=="
      value: "COMPLETE"
    - field: SPECIES_OBS
      operator: "species_scheme_compatible"
      value: true
  actions:
    - field: MMS109
      value: "PASS"
    - field: COMMENT
      value: "MMS109 Manual PASS as MLST scheme appropriate for SPECIES_OBS"  

