# Species to MLST Scheme Mapping
# This file maps observed species to their corresponding MLST schemes
# Add only the schemes that are returned as FALSE in the TEST_SCHEME field but should be TRUE
# Format: scheme_name -> list of species that can use this scheme

ecoli_achtman_4:
  - "Escherichia albertii"
  - "Escherichia species"

smaltophilia:
  - "Stenotrophomonas species"

# Add more mappings as needed
# Example:
# campylobacter:
#   - "Campylobacter jejuni"
#   - "Campylobacter coli"
#   - "Campylobacter species"
